# config/app.yml for rails-settings-cached
defaults: &defaults
  # default audio coded faac is not available on all ffmpeg versions, aac good enough
  audio_codec: 'aac'
  # using sendfile header for Share Download
  proxy: 'nginx'
  default_timezone: 'Europe/Berlin'
  tesseract_language: 'eng+deu'
  storage:
    original: 'aws'
    large: 'aws'
    default: 'file'

  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    access_key_secret: <%= ENV['AWS_ACCESS_KEY_SECRET'] %>
    region: <%= ENV['AWS_REGION'] || 'eu-west-1' %>
    bucket: <%= ENV['AWS_BUCKET'] || 'private' %>
    acl: <%= ENV['AWS_ACL'] || 'private' %>

  rekognition:
    enabled: true
    # When querying labels = tags for images, take the top 20 tags which have a
    # confidence of more than 40%
    labels:
      max_labels: 20
      min_confidence: 40

    faces:
      rekognition_collection: <%= ENV['AWS_REKOGNITION_COLLECTION'] %>
      enabled: true
      auto_assign:
        # Auto-assign new faces, if:
        #   * from the most similar 15 other faces
        #   * with more than 85% similarity
        #   * from only one existing person (or unknown)
        #   * there are at least 10 images of an  existing person in the query set
        enabled: true
        threshold: 85
        max_faces: 15
        min_existing_faces: 10

  # Experimental
  # ocr:
  #   enabled: false
  # elasticsearch:
  #   enabled: false

development:
  <<: *defaults

test:
  <<: *defaults
  default_timezone: 'Europe/Berlin'
  storage:
    original: 'file'
    large: 'file'
    default: 'file'

production:
  <<: *defaults
